// react/src/routes/404.js
import React from "react";
import { Link } from "dva/router";
import { Icon } from "antd";

const NotFound = () => {
  return (
    <div>
      <h1 style={{ color: "#777" }}>404 Page Not Found</h1>
      <Link to="/" style={{ fontSize: "13px", color: "#777" }}>
        <Icon type="arrow-left" /> 返回首页
      </Link>
    </div>
  );
};

export default { NotFound };

// resources/assets/js/components/404.vue
<template>
    <div>
        <el-breadcrumb separator="/">
            <el-breadcrumb-item>404</el-breadcrumb-item>
            <el-breadcrumb-item>Page Not Found</el-breadcrumb-item>
        </el-breadcrumb>
        <h1 style="color: #777">404 Page Not Found</h1>
        <router-link to="/" style="font-size: 13px; color: #777;"><i class="el-icon-arrow-left"></i> 返回首页</router-link>
    </div>
</template>
