// resources/assets/js/components/admin/Rank.vue
<template>
    <div>
    <el-breadcrumb separator="/">
        <el-breadcrumb-item>投票结果</el-breadcrumb-item>
        <el-breadcrumb-item>Rank</el-breadcrumb-item>
    </el-breadcrumb>
    <div class="main">
            <el-table :data="rank" v-loading.body="tableLoading" element-loading-text="加载中..." max-height="500" style="width: 100%" stripe>
                <el-table-column prop="id" label="#" width="55"></el-table-column>
                <el-table-column prop="playtime" label="时段" :filters="filters" :filter-method="filterPlaytime" filter-placement="bottom-end" width="70px"></el-table-column>
                <el-table-column prop="name" label="曲名"></el-table-column>
                <el-table-column prop="score" label="得分" sortable></el-table-column>
                <el-table-column prop="sum" label="总分" sortable></el-table-column>
                <el-table-column prop="counts" label="投票人数" sortable></el-table-column>
                <el-table-column type="expand">
                    <template slot-scope="props">
                        <el-form label-position="left" inline>
                            <el-form-item label="时段">
                                <span>{{ props.row.playtime }}</span>
                            </el-form-item>
                            <el-form-item label="曲名">
                                <span>{{ props.row.name }}</span>
                            </el-form-item>
                            <el-form-item label="来源">
                                <span>{{ props.row.origin }}</span>
                            </el-form-item>
                            <el-form-item label="得分">
                                <span>{{ props.row.score }}</span>
                            </el-form-item>
                            <el-form-item label="总分">
                                <span>{{ props.row.sum }}</span>
                            </el-form-item>
                            <el-form-item label="投票人数">
                                <span>{{ props.row.counts }}</span>
                            </el-form-item>
                            <el-form-item label="试听">
                                <span><audio :src="props.row.url" v-if="props.row.url" controls="controls"></audio></span>
                            </el-form-item>
                        </el-form>
                    </template>
                </el-table-column>
            </el-table>
            <div style="margin-top: 20px">
                <el-button type="primary" @click="showResult = ! showResult">{{ showResult ? '收起' : '生成'}}结果</el-button>
                <transition name="el-fade-in-linear">
                    <el-input type="textarea" v-model="result" v-show="showResult" :autosize="{ minRows: 5, maxRows: 20}" style="margin-top: 10px"></el-input>
                </transition>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                type: '',
                url: '/Manage/Rank',
                tableLoading: false,
                btnLoading: false,
                error: false,
                rank: null,
                showResult: false,
                filters: [
                    { text: '6:30', value: '1' },
                    { text: '7:00', value: '2' },
                    { text: '13:45', value: '3' },
                    { text: '18:40', value: '4' },
                    { text: '21:35', value: '5' },
                    { text: '22:30', value: '6' }
                ]
            }
        },
        created() {
            this.getRank()
        },
        computed: {
            result: function() {
                if(this.rank != null) {
                    let result = JSON.parse(JSON.stringify(this.rank)) //!important:  Copy Array
                    result.forEach(v => {
                            this.$delete(v, 'sum')
                            this.$delete(v, 'counts')
                        })
                    return JSON.stringify(result);
                } else {
                    return null;
                }
            },
        },
        methods: {
            filterPlaytime(value, row) {
                return row.playtime === value;
            },
            getRank() {
                this.tableLoading = true
                axios.get(this.url)
                .then((res) => {
                    this.tableLoading = false
                    if(res.data.error == 0) {
                        this.rank = res.data.songs
                    } else {
                        this.$message.error('获取数据失败');
                    }
                })
                .catch((err) => {
                    this.tableLoading = false
                    console.log(err);
                });
            }
        }
    }
</script>

// react/src/routes/manage/rank.jsx
import React, { useState } from "react";
import { Form, Table, Button, Input, Modal } from "antd";
import { timeFilters } from "config";
import InlineForm from "components/admin/InlineForm";
import { InlineFormRow } from "components/admin/InlineForm";
import Title from "hooks/useTitle";
import { useRank } from "services/admin/rank";

const { TextArea } = Input;
const FormItem = Form.Item;
const columns = [
  { dataIndex: "id", title: "#", width: "60px" },
  {
    dataIndex: "playtime",
    title: "时段",
    width: "80px",
    filters: timeFilters,
    onFilter: (value, record) => record.playtime === value
  },
  { dataIndex: "name", title: "曲名" },
  {
    dataIndex: "score",
    title: "得分",
    sorter: (a, b) => a.score - b.score
  },
  {
    dataIndex: "sum",
    title: "总分",
    sorter: (a, b) => a.sum - b.sum
  },
  {
    dataIndex: "counts",
    title: "投票人数",
    sorter: (a, b) => a.counts - b.counts
  }
];

const Rank = () => {
  const rank = useRank();
  const [showResult, setShowResult] = useState(false);

  const handleCancel = () => {
    setShowResult(false);
  };

  const result = () => {
    let result = JSON.parse(JSON.stringify(rank.data)); //!important:  Copy Array
    result.forEach((v) => {
      delete v.sum;
      delete v.counts;
    });
    return JSON.stringify(result);
  };

  const renderExpanded = (row) => (
    <InlineForm>
      <InlineFormRow>
        <FormItem label="时段">{row.playtime}</FormItem>
        <FormItem label="曲名">{row.name}</FormItem>
        <FormItem label="来源">{row.origin}</FormItem>
      </InlineFormRow>
      <InlineFormRow>
        <FormItem label="得分">{row.score}</FormItem>
        <FormItem label="总分">{row.sum}</FormItem>
        <FormItem label="票数">{row.counts}</FormItem>
      </InlineFormRow>
      <InlineFormRow>
        <FormItem label="试听">
          <audio src={row.url} controls="controls" preload="none" />
        </FormItem>
      </InlineFormRow>
    </InlineForm>
  );

  return (
    <>
      <Title>投票结果</Title>
      <Table
        dataSource={rank.data}
        columns={columns}
        loading={rank.isLoading}
        expandedRowRender={renderExpanded}
        scroll={{ x: 600 }}
        rowKey="id"
      />
      <Button type="primary" onClick={() => setShowResult(true)}>
        生成结果
      </Button>
      {showResult && (
        <Modal
          open={showResult}
          onCancel={handleCancel}
          title="生成投票结果"
          footer={[
            <Button key="cancel" onClick={handleCancel}>
              关闭
            </Button>
          ]}
          style={{ top: "70px" }}
        >
          <TextArea value={result()} autoSize={{ minRows: 6, maxRows: 10 }} />
        </Modal>
      )}
    </>
  );
};

export default Rank;
