// resources/assets/js/components/Footer.vue
<template>
	<footer><hr>
        <div class="footer">
            <p>Copyright © 2007-2017 FZYZ SCAN@7HMakers. All rights reserved.<br>
            Past Maintainer: <a href="https://blog.robotshell.org">Robot</a> <a href="http://blog.miskcoo.com">Miskcoo</a> <a href="https://www.upsuper.org">Upsuper</a><br>
            Now Maintainer: Googleplex
            </p>
        </div>
    </footer>
</template>

<style>
footer {
    display: block;
    position: relative;
    bottom: 0;
    width: 100%;
    font-size: 85%;
    box-sizing: border-box;
}
.footer {
    padding-left: 1.6rem;
    color: #777;
}
.footer a{
    text-decoration: underline;
}
</style>

// react/src/components/Footer/index.jsx
import React from "react";
import { Layout } from "antd";
import styles from "./index.less";

const Footer = () => {
  const Year = () => {
    const date = new Date();
    return date.getFullYear();
  };

  return (
    <Layout.Footer className={styles.footer}>
      Copyright © 2009-
      {Year()} FZYZ SCAN & 7HMakers. All rights reserved.
      <br />
      Author: <a href="https://github.com/y-young/f1music">Googleplex</a>
      <br />
      v1.x(2009-2016) Author: <a href="https://www.upsuper.org">Upsuper</a>
      <br />
      Past Maintainers: <a href="https://blog.robotshell.org">Robot</a>&nbsp;
      <a href="http://blog.miskcoo.com">Miskcoo</a>&nbsp;
      <a href="https://mengxiaolin.me/">linmx0130</a>
    </Layout.Footer>
  );
};

export default Footer;
