// react/src/routes/Login.js
import React from "react";
import { connect } from "dva";
import styles from "./Login.css";
import { Link } from "dva/router";
import { Form, Icon, Button, Input, Alert } from "antd";

const FormItem = Form.Item;

const Login = ({
  loading,
  dispatch,
  error,
  msg,
  form: { getFieldDecorator, validateFieldsAndScroll }
}) => {
  const handleSubmit = () => {
    validateFieldsAndScroll((errors, values) => {
      if (errors) {
        return;
      }
      dispatch({ type: "login/login", payload: values });
    });
  };

  const validatePassword = (rule, value, callback) => {
    if (value === "123456") {
      callback("为保证投票质量目前禁止使用校网初始密码登录,请更改密码");
    }
    callback();
  };

  return (
    <div>
      <div className={styles.login}>
        <div style={{ width: "300px", margin: "auto" }}>
          <div
            style={{
              fontSize: "30px",
              textAlign: "center",
              marginBottom: "20px"
            }}
          >
            <b>登录</b>
          </div>
          <Form>
            <FormItem hasFeedback>
              {getFieldDecorator("stuId", {
                rules: [
                  { required: true, message: "请输入学号" },
                  { min: 10, message: "学号应为10或11位" },
                  { max: 11, message: "学号应为10或11位" }
                ]
              })(<Input placeholder="学号" />)}
            </FormItem>
            <FormItem hasFeedback>
              {getFieldDecorator("password", {
                rules: [
                  { required: true, message: "请输入密码" },
                  { validator: validatePassword }
                ]
              })(<Input type="password" placeholder="校园网密码" />)}
            </FormItem>
            <FormItem>
              <Button
                type="primary"
                onClick={handleSubmit}
                loading={loading}
                style={{ width: "100%" }}
              >
                登录
              </Button>
            </FormItem>
          </Form>
          <Link to="/" style={{ fontSize: "13px", color: "#777" }}>
            <Icon type="arrow-left" /> 返回首页
          </Link>
        </div>
      </div>
      <canvas width="1080" height="1608" id="curve" />
    </div>
  );
};

function mapStateToProps(state) {
  const { error, msg } = state.login;
  return { loading: state.loading.models.login, error, msg };
}

export default connect(mapStateToProps)(Form.create()(Login));

// resources/assets/js/Login.vue
<template>
    <div class="app">
        <div style="width: 300px; margin: auto;">
            <div style="line-height: 36px; font-size: 20px; text-align: center; margin-bottom: 20px;"><b>登录</b></div>
            <div v-show="loginSuccess">
                <el-alert title="登录成功，正在跳转..." type="success"></el-alert><br>
            </div>
            <div v-show="errorMsg">
                <el-alert :title="errorMsg" type="error"></el-alert><br>
            </div>
            <el-form :model="ruleForm" :rules="rules" ref="ruleForm">
                <el-form-item prop="stuId">
                    <el-input v-model="ruleForm.stuId" placeholder="学号"></el-input>
                </el-form-item>
                <el-form-item prop="password">
                    <el-input type="password" v-model="ruleForm.password" placeholder="校园网密码"></el-input>
                </el-form-item>
                <el-form-item>
                    <el-button type="primary" :loading="loading" @click="login" style="width: 300px;">{{ loading ? "登录中" : "登录" }}</el-button>
                </el-form-item>
            </el-form>
        </div>
    </div>
</template>

<script>
    var validatestuId = (rule, value, callback) => {
        if (value === '') {
            callback(new Error('请输入学号'));
        } else if (value.length != 11) {
            callback(new Error('长度应为11个字符'));
        } else {
            callback();
        }
    };
    var validatepass = (rule, value, callback) => {
        if (value == '') {
            callback(new Error('请输入密码'));
        } else if (value.length == '123456') {
            callback(new Error('为保证投票质量目前禁止使用校网初始密码登录,请更改密码'));
        } else {
            callback();
        }
    };
    export default {
        data() {
            return {
                ruleForm: {
                    stuId: '',
                    password: ''
                },
                loading: false,
                loginSuccess: false,
                errorMsg: '',
                rules: {
                    stuId: [
                        { validator: validatestuId, trigger: 'blur' }
                    ],
                    password: [
                        { validator: validatepass, trigger: 'blur'}
                    ]
                }
            }
        },
        methods: {
            login: function() {
                this.$refs['ruleForm'].validate((valid) => {
                    if (valid) {
                        this.loading = true
                        this.errorMsg = ""
                        axios.post('/Login',{
                            stuId: this.ruleForm.stuId,
                            password: this.ruleForm.password
                        })
                        .then((res) => {
                            this.loading = false
                            if(res.data.error == '0') {
                                this.loginSuccess = true
                                location.href = "/"
                            } else {
                                this.errorMsg = res.data.msg
                            }
                        })
                        .catch((err) => {
                            this.loading = false
                            console.log(err);
                        });
                    } else {
                        this.errorMsg = "请修正所有错误后再提交"
                        return false;
                    }
                });
            }
        }
    }
</script>

<style>
    canvas {
         position: absolute;
         top: 0;
         left: 0;
         z-index: -1;
         width: 100%;
         height: 100%;
         pointer-events: none;
    }
    .app {
         position: absolute;
         left: 0;
         width: 320px;
         text-align: center;
         top: 50%;
         left: 50%;
         margin-left: -160px;
         margin-top: -160px;
    }
</style>
