// resources/assets/js/components/admin/Songs.vue
<template>
    <div>
    <el-breadcrumb separator="/">
        <el-breadcrumb-item>曲目</el-breadcrumb-item>
        <el-breadcrumb-item>Songs</el-breadcrumb-item>
    </el-breadcrumb>
    <div class="main">
            <div style="font-size: 14px; color: #777">曲目总数: {{ allCnt }} 首 已选中: {{ selectedCnt }} 首</div><br>
            <el-table :data="songs" @selection-change="handleSelectionChange" v-loading.body="tableLoading" element-loading-text="加载中..." max-height="500" style="width: 100%" stripe>
                <el-table-column type="selection" width="45"></el-table-column>
                <el-table-column prop="id" label="#" width="55"></el-table-column>
                <el-table-column prop="playtime" label="时段" :filters="filters" :filter-method="filterPlaytime" filter-placement="bottom-end" width="70px"></el-table-column>
                <el-table-column prop="name" label="曲名"></el-table-column>
                <el-table-column prop="reports_count" label="举报数" sortable></el-table-column>
                <el-table-column prop="created_at" label="时间" sortable></el-table-column>
                <el-table-column type="expand">
                    <template scope="props">
                        <el-form label-position="left" inline>
                            <el-form-item label="时段">
                                <span>{{ props.row.playtime }}</span>
                            </el-form-item>
                            <el-form-item label="曲名">
                                <span>{{ props.row.name }}</span>
                            </el-form-item>
                            <el-form-item label="来源">
                                <span>{{ props.row.origin }}</span>
                            </el-form-item>
                            <el-form-item label="举报数">
                                <span>{{ props.row.reports_count }}</span>
                            </el-form-item>
                            <el-form-item label="创建时间">
                                <span>{{ props.row.created_at }}</span>
                            </el-form-item>
                            <el-form-item label="最后更改时间">
                                <span>{{props.row.updated_at}}</span>
                            </el-form-item>
                            <el-form-item label="试听">
                                <span><i class="el-icon-loading" v-if="!props.row.file.url"></i><audio :src="props.row.file.url" v-if="props.row.file.url" controls="controls"></audio></span>
                            </el-form-item>
                            <el-form-item label="操作">
                                <span>
                                    <el-button @click="edit(props.row.id)">查看/编辑</el-button>
                                    <span v-if="type == 'trashed'">
                                        <el-button @click="restore(props.row.id, props.row)" :loading="restoreLoading">恢复</el-button>
                                        <el-button type="danger" @click="del(props.row.id, props.row)" :loading="delLoading">彻底删除</el-button>
                                    </span>
                                    <span v-else>
                                        <el-button type="danger" @click="trash(props.row.id, props.row)" :loading="delLoading">删除</el-button>
                                    </span>
                                </span>
                            </el-form-item>
                        </el-form>
                    </template>
                </el-table-column>
            </el-table>
            <div style="margin-top: 20px">
                <el-button type="danger" @click="batchTrash" :loading="delLoading">删除所选</el-button>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                type: '',
                url: '/Manage/Songs',
                tableLoading: false,
                delLoading: false,
                restoreLoading: false,
                error: false,
                allCnt: 0,
                selectedCnt: 0,
                songs: null,
                mp3: '',
                fileList: [],
                filters: [
                    { text: '6:30', value: '1' },
                    { text: '7:00', value: '2' },
                    { text: '13:45', value: '3' },
                    { text: '18:40', value: '4' },
                    { text: '21:35', value: '5' },
                    { text: '22:30', value: '6' }
                ],
                selected: []
            }
        },
        created() {
            this.getSongs()
        },
        watch: {
            '$route': 'getSongs',
            'songs': function() {
                this.allCnt = this.songs.length
            },
            'selected': function() {
                this.selectedCnt = this.selected.length
            }
        },
        methods: {
            filterPlaytime(value, row) {
                return row.playtime === value;
            },
            edit(id) {
                this.$router.push('/Song/Edit/' + id);
            },
            trash(id, row) {
                let index = this.songs.indexOf(row); //Ugly Solution
                this.delLoading = true
                axios.post('/Manage/Song/Trash', {
                    id: [id]
                })
                .then((res) => {
                    this.delLoading = false
                    if(res.data.error == 0) {
                        this.$message.success('操作成功!');
                        console.log(index);
                        this.songs.splice(index, 1);
                    } else {
                        this.$message.error(res.data.msg);
                    }
                })
                .catch((err) => {
                    this.delLoading = false
                    console.log(err);
                });
            },
            del(id, row) {
                let index = this.songs.indexOf(row); //Ugly Solution
                this.delLoading = true
                axios.post('/Manage/Song/Delete', {
                    id: [id]
                })
                .then((res) => {
                    this.delLoading = false
                    if(res.data.error == 0) {
                        this.$message.success('操作成功!');
                        this.songs.splice(index, 1);
                    } else {
                        this.$message.error(res.data.msg);
                    }
                })
                .catch((err) => {
                    this.delLoading = false
                    console.log(err);
                });
            },
            batchTrash() {
                this.delLoading = true
                axios.post('/Manage/Song/Trash', {
                    id: this.selected
                })
                .then((res) => {
                    this.delLoading = false
                    if(res.data.error == 0) {
                        this.$message.success('操作成功!');
                        setTimeout("location.reload()", 1000);
                    } else {
                        this.$message.error(res.data.msg);
                    }
                })
                .catch((err) => {
                    this.delLoading = false
                    console.log(err);
                });
            },
            restore(id, row) {
                let index = this.songs.indexOf(row); //Ugly Solution
                this.restoreLoading = true
                axios.post('/Manage/Song/Restore', {
                    id: [id]
                })
                .then((res) => {
                    this.restoreLoading = false
                    if(res.data.error == 0) {
                        this.$message.success('操作成功!');
                        this.songs.splice(index, 1);
                    } else {
                        this.$message.error(res.data.msg);
                    }
                })
                .catch((err) => {
                    this.restoreLoading = false
                    console.log(err);
                });
            },
            handleSelectionChange(val) {
                this.selected = val;
                this.selected = this.selected.map(function(song) {
                    return song.id;
                })
            },
            getSongs() {
                this.tableLoading = true
                this.type = this.$route.meta.type
                if(this.type == 'trashed')
                    this.url = '/Manage/Songs/Trashed'
                else
                    this.url = '/Manage/Songs'
                axios.get(this.url)
                .then((res) => {
                    this.tableLoading = false
                    if(res.data.error == 0) {
                        this.songs = res.data.songs
                    } else {
                        this.$message.error('获取数据失败');
                    }
                })
                .catch((err) => {
                    this.tableLoading = false
                    console.log(err);
                });
            }
        }
    }
</script>

// react/src/routes/admin/Songs.js
import React from "react";
import { connect } from "dva";
import { Table, Button, Input, Form, Modal } from "antd";
import { TimeSelector } from "components/admin";

const FormItem = Form.Item;
const columns = [
  {
    dataIndex: "id",
    title: "#",
    width: "60px",
    sorter: (a, b) => a.id - b.id
  },
  {
    dataIndex: "playtime",
    title: "时段",
    width: "70px",
    filters: [
      { text: "6:30", value: "1" },
      { text: "7:00", value: "2" },
      { text: "13:45", value: "3" },
      { text: "18:40", value: "4" },
      { text: "21:35", value: "5" },
      { text: "22:30", value: "6" }
    ],
    onFilter: (value, record) => record.playtime === value
  },
  { dataIndex: "name", title: "曲名" },
  {
    dataIndex: "reports_count",
    title: "举报数",
    sorter: (a, b) => a.reports_count - b.reports_count
  },
  { dataIndex: "created_at", title: "时间" }
];

class Songs extends React.Component {
  state = {
    selectedRowKeys: [],
    modalVisible: false,
    row: null
  };

  onSelectChange = selectedRowKeys => {
    this.setState({ selectedRowKeys: selectedRowKeys });
  }

  editSong = row => {
    this.props.form.resetFields();
    this.setState({ row: row, modalVisible: true });
  };

  handleSave = () => {
    const { dispatch, form } = this.props;
    form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        dispatch({ type: "songs/save", payload: values }).then(success => {
          if (success) {
            this.setState({ modalVisible: false });
          }
        });
      }
    });
  };

  handleCancel = () => {
    this.setState({ modalVisible: false });
  };

  handleDelete = (id, isDelete = false) => {
    const { dispatch } = this.props;
    if (isDelete) {
      dispatch({ type: "songs/delete", payload: id });
    } else {
      dispatch({ type: "songs/trash", payload: id });
    }
    this.setState({ selectedRowKeys: [] });
  };

  handleBatchDelete = (isDelete = false) => {
    console.log(this.state.selectedRowKeys);
    console.log(isDelete);
    this.handleDelete(this.state.selectedRowKeys, isDelete);
  };

  handleRestore = id => {
    const { dispatch } = this.props;
    dispatch({ type: "songs/restore", payload: id });
    this.setState({ selectedRowKeys: [] });
  };

  handleBatchRestore = () => {
    this.handleRestore(this.state.selectedRowKeys);
  };

  renderExpanded = row => {
    const { songs, loading } = this.props;
    const { type } = songs;

    return (
      <div>
        <Form layout="inline">
          <FormItem label="时段">{row.playtime}</FormItem>
          <FormItem label="曲名">{row.name}</FormItem>
          <FormItem label="来源">{row.origin}</FormItem>
          <br />
          <FormItem label="创建时间">{row.created_at}</FormItem>
          <FormItem label="最后更新时间">{row.updated_at}</FormItem>
          <FormItem label="删除时间">{row.deleted_at}</FormItem>
          <br />
          <FormItem label="试听">
            <audio src={row.file.url} controls="controls" />
          </FormItem>
          <FormItem label="操作">
            <Button
              type="primary"
              icon="edit"
              onClick={() => this.editSong(row)}
            >
              编辑
            </Button>
            {type === "trashed" ? (
              <span>
                <Button
                  type="secondary"
                  icon="rollback"
                  onClick={() => this.handleRestore([row.id])}
                  loading={loading.effects["songs/restore"]}
                >
                  恢复
                </Button>
                <Button
                  type="danger"
                  icon="delete"
                  onClick={() => this.handleDelete([row.id], true)}
                  loading={loading.effects["songs/delete"]}
                >
                  彻底删除
                </Button>
              </span>
            ) : (
              <Button
                type="danger"
                icon="delete"
                onClick={() => this.handleDelete([row.id])}
                loading={loading.effects["songs/trash"]}
              >
                删除
              </Button>
            )}
          </FormItem>
        </Form>
      </div>
    );
  };

  render() {
    const { songs, loading, form } = this.props;
    const { type, list } = songs;
    const { getFieldDecorator } = form;
    const { selectedRowKeys, row, modalVisible } = this.state;
    const rowSelection = {
      selectedRowKeys,
      onChange: this.onSelectChange
    };

    return (
      <div>
        <div style={{ fontSize: "14px", color: "#777" }}>
          曲目总数: {list.length} 首 已选中: {selectedRowKeys.length} 首
        </div>
        <br />
        <Table
          dataSource={list}
          columns={columns}
          rowSelection={rowSelection}
          expandedRowRender={this.renderExpanded}
          loading={loading.effects["songs/fetch"]}
          rowKey="id"
          scroll={{ x: 600 }}
          style={{ width: "100%" }}
        />
        {row && (
          <Modal
            visible={modalVisible}
            onCancel={this.handleCancel}
            confirmLoading={loading.effects["songs/save"]}
            okText="保存"
            title="编辑曲目"
            onOk={this.handleSave}
            style={{ top: "60px" }}
          >
            <Form>
              {getFieldDecorator("id", { initialValue: row.id })(
                <Input type="hidden" />
              )}
              <FormItem label="时段">
                {getFieldDecorator("playtime", { initialValue: row.playtime })(
                  <TimeSelector style={{ width: "120px" }} />
                )}
              </FormItem>
              <FormItem label="曲名">
                {getFieldDecorator("name", {
                  initialValue: row.name,
                  rules: [{ required: true, message: "请填写曲名" }]
                })(<Input placeholder="曲名" />)}
              </FormItem>
              <FormItem label="来源">
                {getFieldDecorator("origin", { initialValue: row.origin })(
                  <Input placeholder="来源" />
                )}
              </FormItem>
            </Form>
          </Modal>
        )}
        {type === "trashed" ? (
          <span>
            <Button
              type="secondary"
              onClick={this.handleBatchRestore}
              loading={loading.effects["songs/restore"]}
            >
              恢复所选
            </Button>
            <Button
              type="danger"
              onClick={() => this.handleBatchDelete(true)}
              loading={loading.effects["songs/delete"]}
            >
              彻底删除所选
            </Button>
          </span>
        ) : (
          <Button
            type="danger"
            onClick={() => this.handleBatchDelete(false)}
            loading={loading.effects["songs/trash"]}
          >
            删除所选
          </Button>
        )}
      </div>
    );
  }
}

export default connect(({ songs, loading }) => ({ songs, loading }))(
  Form.create()(Songs)
);
