// resources/assets/js/components/Footer.vue
<template>
	<footer><hr>
        <div class="footer">
            <p>Copyright © 2007-2018 FZYZ SCAN. All rights reserved.<br>
            Past Maintainer: <a href="https://blog.robotshell.org">Robot</a> <a href="http://blog.miskcoo.com">Miskcoo</a> <a href="https://www.upsuper.org">Upsuper</a><br>
            Author & Current Maintainer: Googleplex
            </p>
        </div>
    </footer>
</template>

<style>
footer {
    display: block;
    position: relative;
    bottom: 0;
    width: 100%;
    font-size: 85%;
    box-sizing: border-box;
}
.footer {
    padding-left: 1.6rem;
    padding-right: 1.6rem;
    color: #777;
}
.footer a{
    text-decoration: underline;
}
</style>

// react/src/components/Footer.js
import React from "react";
import { Layout } from "antd";

const Footer = () => {
  const Year = () => {
    const date = new Date();
    return date.getFullYear();
  };

  return (
    <Layout.Footer className="footer">
      Copyright © 2007-{Year()} FZYZ SCAN & 7HMakers. All rights reserved.<br />
      Author & Current Maintainer: Googleplex<br />
      Past Maintainers: <a href="https://blog.robotshell.org">
        Robot
      </a>{" "}
      <a href="http://blog.miskcoo.com">Miskcoo</a>{" "}
      <a href="https://www.upsuper.org">Upsuper</a>
    </Layout.Footer>
  )
}

export default Footer;
