// resources/assets/js/components/Sidebar.vue
<template>
    <div class="sidebar">
        <div class="logo">福州一中 校园音乐征集</div>
            <el-menu mode="vertical" :default-active="activeIndex" :default-openeds="isDesktop ? ['4'] : []" class="nav" :router="true">
                <el-menu-item index="1" :route="{ name: 'Home' }"><i class="fa fa-home"></i>首页</el-menu-item>
                <el-menu-item index="2" :route="{ name: 'Upload' }"><i class="fa fa-upload"></i>上传</el-menu-item>
                <el-menu-item index="5" :route="{ name: loggedIn ? 'Logout' : 'Login' }">
                    <i class="fa" :class="[loggedIn ? 'fa-sign-out' : 'fa-sign-in']"></i>{{ loggedIn ? '登出' : '登录' }}
                </el-menu-item>
                <el-submenu index="4">
                    <template slot="title"><i class="fa fa-check-square-o"></i>投票</template>
                    <el-menu-item index="4-1" :route="{ path: '/Vote/1' }"> 6:30 起床铃</el-menu-item>
                    <el-menu-item index="4-2" :route="{ path: '/Vote/2' }"> 7:00 早出门</el-menu-item>
                    <el-menu-item index="4-3" :route="{ path: '/Vote/3' }">13:45 午出门</el-menu-item>
                    <el-menu-item index="4-4" :route="{ path: '/Vote/4' }">18:40 晚出门</el-menu-item>
                    <el-menu-item index="4-5" :route="{ path: '/Vote/5' }">21:35 晚自习结束</el-menu-item>
                    <el-menu-item index="4-6" :route="{ path: '/Vote/6' }">22:30 熄灯铃</el-menu-item>
                </el-submenu>
            </el-menu>
    </div>
</template>

<script>
    export default {
        props: ['activeIndex', 'loggedIn', 'isDesktop'],
    }
</script>

<style>
.sidebar{
    position: absolute;
    width: 300px;
    top: 0;
    left: -300px;
    bottom: 0;
    z-index: 1;
    overflow-y: auto;
    -webkit-transition: left 250ms ease;
    -moz-transition: left 250ms ease;
    -o-transition: left 250ms ease;
    transition: left 250ms ease;
}
@media (max-width:500px) {
    .sidebar {
        width: calc(100% - 60px);
        bottom: 0;
        left: calc(60px - 100%);
    }
    .logo {
        width: calc(100% - 60px);
    }
}
.app.show-sidebar .sidebar {
    left: 0;
}
.nav {
    display: block;
    position: absolute;
    top: 60px;
    bottom: 0;
    margin: 0;
    width: 100%;
    -webkit-transition: left 250ms ease;
    -moz-transition: left 250ms ease;
    -o-transition: left 250ms ease;
    transition: left 250ms ease;
}
.nav a {
    text-decoration: none;
}
.logo {
    position: fixed;
    top: 0;
    width: calc(100% - 60px);
    padding: 0 15px;
    transition: all 250ms ease;
    font-size: 20px;
    line-height: 60px;
    z-index: 2;
    color: #fff;
    border-color: rgba(238,241,146,0.3);
    border-right-width: 1px;
    border-right-style: solid;
    background: #20a0ff;
    overflow: hidden;
}
</style>

// react/src/components/Sidebar.js
import React from "react";
import classnames from "classnames";
import { Link } from "dva/router";
import { Menu, Icon, Layout } from "antd";
import styles from "./Sidebar.css";

const SubMenu = Menu.SubMenu;
const { Header } = Layout;

const Sidebar = props => {
  const sidebarClass = classnames({
    [styles.sidebar]: true,
    [styles.show]: !props.collapsed
  });

  return (
    <div className={sidebarClass}>
      <Header className={styles.logo}>福州一中 校园音乐征集</Header>
      <Menu
        className={styles.nav}
        mode="inline"
        selectedKeys={[props.location.pathname]}
        defaultOpenKeys={props.desktop ? ["/vote"] : []}
      >
        <Menu.Item key="/">
          <Link to="/">
            <Icon type="home" />首页
          </Link>
        </Menu.Item>
        <Menu.Item key="/login">
          <Link to={props.loggedIn ? "/logout" : "/login"}>
            <Icon type={props.loggedIn ? "logout" : "login"} />
            {props.loggedIn ? "登出" : "登录"}
          </Link>
        </Menu.Item>
        <Menu.Item key="/upload">
          <Link to="/upload">
            <Icon type="upload" />上传
          </Link>
        </Menu.Item>
        <SubMenu
          key="/vote"
          title={
            <span>
              <Icon type="form" />
              <span>投票</span>
            </span>
          }
        >
          <Menu.Item key="/vote/1">
            <Link to="/vote/1">6:30 起床铃</Link>
          </Menu.Item>
          <Menu.Item key="/vote/2">
            <Link to="/vote/2">7:00 早出门</Link>
          </Menu.Item>
          <Menu.Item key="/vote/3">
            <Link to="/vote/3">13:45 午出门</Link>
          </Menu.Item>
          <Menu.Item key="/vote/4">
            <Link to="/vote/4">18:40 晚出门</Link>
          </Menu.Item>
          <Menu.Item key="/vote/5">
            <Link to="/vote/5">21:35 晚自习结束</Link>
          </Menu.Item>
          <Menu.Item key="/vote/6">
            <Link to="/vote/6">22:30 熄灯铃</Link>
          </Menu.Item>
        </SubMenu>
      </Menu>
    </div>
  );
};

export default Sidebar;
