// resources/assets/js/components/YPlayer.vue
<template>
    <div class="yplayer">
        <audio id="audio" @durationchange="init" @timeupdate="progress" @progress="onLoad" @ended="end" @error="error" :src="src" ref="player" preload="metadata"></audio>
        <div class="control" v-if="detail">
            <el-slider v-model="currentTime" :min="0" :max="audio.duration" :show-tooltip="false"></el-slider>
            <div id="timeDetail">{{ played }} / {{ duration }}</div>
        </div>
        <el-button-group id="controls">
            <el-button type="primary" @click="play"><i class="fa" v-bind:class="[isPlaying ? 'fa-pause' : 'fa-play']" style="margin-right: 0;"></i></el-button>
            <el-button type="primary" @click="stop" v-if="detail"><i class="fa fa-stop" style="margin-right: 0;"></i></el-button>
        </el-button-group>
        <!--<div class="control" v-if="detail">
           {{ loaded }}
        </div>-->
    </div>
</template>

<script>
    export default {
        props: {
            src: {
                type: String,
                required: true
            },
            detail: {
                type: Boolean,
                default: true
            }
        },
        data() {
            return {
                currentTime: 0,
                totalTime: 0,
                isPlaying: false,
                loaded: 0,
                audio: ''
            }
        },
        mounted() {
            this.audio = this.$refs.player
        },
        computed: {
            played: function() {
                return formatTime(this.currentTime)
            },
            duration: function() {
                return formatTime(this.totalTime)
            }
        },
        methods: {
            init: function() {
                this.totalTime = this.audio.duration
                //this.$set(this, 'duration', formatTime(this.totalTime)) //this.duration = formatTime(this.totalTime)
            },
            progress: function() {
                this.currentTime = this.audio.currentTime
                this.$emit('progress', Number(this.currentTime))
            },
            play: function() {
                if(!this.isPlaying) {
                    this.audio.play();
                } else {
                    this.audio.pause();
                }
                this.isPlaying = !this.isPlaying;
            },
            stop: function() {
                this.audio.pause();
                this.isPlaying = false;
                this.audio.currentTime = 0;
            },
            end: function() {
                this.audio.pause();
                this.isPlaying = false;
                this.$emit('end')
            },
            onLoad: function() {
                this.loaded = this.audio.buffered.length ? this.audio.buffered.end(this.audio.buffered.length - 1) / this.audio.duration : 0
            },
            error: function() {
                this.$message.error({
                    showClose: true,
                    message: '播放出错了,请重试'
                });
                this.audio.pause()
            },
            changeVolume: function(volume) {
                this.audio.volume = volume / 100
                return volume;
            }
        }
    };

    function formatTime(seconds) {
        if (isNaN(seconds))
            return '00:00';
        const min = parseInt(seconds / 60);
        const sec = parseInt(seconds - min * 60);
        const hours = parseInt(min / 60);
        const newMin = parseInt((seconds / 60) - (60 * parseInt((seconds / 60) / 60)));
        const add0 = (num) => {
            return num < 10 ? '0' + num : '' + num;
        };
        return seconds >= 3600 ? add0(hours) + ':' + add0(newMin) + ':' + add0(sec) : add0(min) + ':' + add0(sec);
    }
</script>

<style>
    #controls {
        float: left;
        margin-right: 20px;
    }
    #volume {
        float: left;
        vertical-align: middle;
        margin-right: 15px;
        padding-top: 10px;
    }
    #changeVolume {
        width: 80px;
        float: left;
    }
    #timeDetail {
        font-size: 12px;
        color: #777;
        display: inline;
        float: right;
    }
</style>

// react/src/components/YPlayer.js
import React from "react";
import _ from "lodash";
import styles from "./YPlayer.css";
import { Button, Slider, Icon, message } from "antd";

const ButtonGroup = Button.Group;

class YPlayer extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      playing: false,
      duration: 0,
      time: 0,
      loaded: 0
    };
    this.updateTime = _.throttle(this.updateTime, 200);
  }

  onTimeUpdate = event => {
    this.updateTime(event.target.currentTime);
  };

  audio = () => {
    return this.audio;
  };

  init = () => {
    this.setState({
      time: 0,
      playing: false
    });
  };

  play = (disableWarning) => {
    if (!this.state.playing) {
      //const promise = this.audio.play();
      this.audio.play();
      /*if (promise) {
        promise.catch((e) => {
          console.warn(e);
          if (e.name === 'NotAllowedError') {
            //this.stop();
            if (!disableWarning) {
                message.warning('您的浏览器可能不兼容自动播放功能,请尝试手动播放');
            }
          }
        });
      }*/
      this.setState({ playing: true });
    }
  };

  pause = () => {
    if (this.state.playing) {
      this.audio.pause();
      this.setState({ playing: false });
    }
  }
    
  toggle = () => {
    if (this.state.playing) {
      this.pause();
    } else {
      this.play();
    }
  };

  stop = () => {
    this.pause();
    this.audio.currentTime = 0;
  };

  onLoad = () => {
    const loaded = this.audio.buffered.length
      ? this.audio.buffered.end(this.audio.buffered.length - 1) /
        this.state.duration
      : 0;
    const percent = (loaded * 100).toFixed(2);
    this.setState({ loaded: percent });
  };

  updateDuration = e => {
    e.persist();
    //console.log(e.target.duration);
    this.setState({ duration: e.target.duration });
  };

  updateTime = time => {
    this.setState({ time: time });
    if (this.props.onProgress) {
      this.props.onProgress(time);
    }
  };

  ended = () => {
    this.setState({ playing: false });
    this.props.onEnded();
  };

  onError = () => {
    this.stop();
    message.error("播放出错了,请重试");
  };

  render() {
    const { mini } = this.props;
    const loaded = this.state.loaded;
    return (
      <div>
        <audio
          ref={audio => {
            this.audio = audio;
          }}
          //controls="controls"
          src={this.props.src}
          onProgress={this.onLoad}
          onTimeUpdate={this.onTimeUpdate}
          onDurationChange={this.updateDuration}
          onPause={() => this.setState({ playing: false })}
          onEnded={this.ended}
          onError={this.onError}
          preload="none"
        />
        {!mini && (
          <div>
            <Slider
              value={this.state.time}
              max={this.state.duration}
              tipFormatter={null}
            />
            <div className={styles.timeDetail}>
              {this.formatTime(this.state.time)} /{" "}
              {this.formatTime(this.state.duration)}
            </div>
          </div>
        )}
        <ButtonGroup className={styles.controls}>
          <Button type="primary" onClick={this.toggle}>
            <Icon type={this.state.playing ? "pause" : "caret-right"} />
          </Button>
          <Button type="primary" onClick={this.stop}>
            <Icon type="step-backward" />
          </Button>
        </ButtonGroup>
        {!mini && (
          <div style={{ width: "5px", float: "left" }}>
            {loaded !== 0.00 && loaded !== 100.00 && loaded + "%"}
          </div>)
         }
      </div>
    );
  }

  formatTime(seconds) {
    if (isNaN(seconds)) return "00:00";
    const min = parseInt(seconds / 60, 10);
    const sec = parseInt(seconds - min * 60, 10);
    const hours = parseInt(min / 60, 10);
    const newMin = parseInt(
      seconds / 60 - 60 * parseInt(seconds / 60 / 60, 10),
      10
    );
    const add0 = num => {
      return num < 10 ? "0" + num : "" + num;
    };
    return seconds >= 3600
      ? add0(hours) + ":" + add0(newMin) + ":" + add0(sec)
      : add0(min) + ":" + add0(sec);
  }
}

export default YPlayer;
